### ISSUE TITLE
feat: support for chunked bigfiles

### ISSUE THREAD

**Issue by michal-kapala** [electroball09/GRPExplorerRust#1]
This is a feature idea for GRFS where bigfile consists of 4 files:
- `Yeti.big`
- `Yeti.big1`
- `Yeti.big2`
- `Yeti.big3`

Currently the tool panics when opening `Yeti.big`:
```
thread 'main' panicked at src\bigfile\metadata.rs:276:97:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf\library/std\src\panicking.rs:665
   1: core::panicking::panic_fmt
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf\library/core\src\panicking.rs:74
   2: core::panicking::panic
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf\library/core\src\panicking.rs:148
   3: core::option::unwrap_failed
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf\library/core\src\option.rs:2012
   4: enum2$<core::option::Option<grp_explorer_rust::bigfile::metadata::ObjectType> >::unwrap
             at %PATH%\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\option.rs:972
   5: grp_explorer_rust::bigfile::metadata::FileEntry::read_from<ref$<slice2$<u8> > >
             at %PATH%\GRPExplorerRust\src\bigfile\metadata.rs:276
   6: grp_explorer_rust::bigfile::io::impl$0::read_file_table
             at %PATH%\GRPExplorerRust\src\bigfile\io.rs:128
   7: grp_explorer_rust::bigfile::Bigfile::load_metadata
             at %PATH%\GRPExplorerRust\src\bigfile\mod.rs:118
   8: grp_explorer_rust::ui::impl$1::update::closure$0::closure$0::closure$0
             at %PATH%\GRPExplorerRust\src\ui\mod.rs:164

...
```

Ive forked to play with the file header structs, we'll see how it goes

**Comment by michal-kapala** [comment]
This is the most detailed access to `SegmentHeader` ive found in GRO:

![seg header](https://github.com/user-attachments/assets/fa5ebe22-2b17-469b-97da-a9f94dc18b38)

After looking at GRO and GRFS data the adjusted structure is:
```rust
pub struct SegmentHeader {
    pub sig: [u8; 4],
    pub unk01: u8, // always 1
    pub num_segments: u8,
    pub segment: u8,
    pub unk02: u8, // always 0
    pub unk_seg_offset01: u64,
    pub header_offset: u64,
    pub unk_seg_offset02: u64,
    pub unk_seg_offset03: u64,
    pub last_update: u64
}
```
`last_update` value comes from [`QueryPerformanceCounter`](https://learn.microsoft.com/en-us/windows/win32/api/profileapi/nf-profileapi-queryperformancecounter)

**Comment by michal-kapala** [comment]
Header data for reference

## GRFS - `Yeti.big`
![grfs1](https://github.com/user-attachments/assets/2b33edaf-1710-49cd-9bd0-a291698ad9f5)

## GRFS - `Yeti.big1`
![grfs2](https://github.com/user-attachments/assets/c188ee1b-69f7-4a1c-87ff-5fdf935e5bbb)

## GRFS - `Yeti.big2`
![grfs3](https://github.com/user-attachments/assets/0c48037f-1760-4f85-82f9-b5c4e000ed65)

## GRFS - `Yeti.big3`
![grfs4](https://github.com/user-attachments/assets/333aacc5-eb51-4fb4-9b4d-91e45c8473a1)

## GRO
![gro](https://github.com/user-attachments/assets/be38a58b-eed9-4e80-a65c-3be822b0b471)

**Comment by michal-kapala** [comment]
Identified 2 more fields:
```rust
pub struct SegmentHeader {
    pub sig: [u8; 4],
    pub unk01: u8, // always 1
    pub num_segments: u8,
    pub segment: u8,
    pub unk02: u8, // always 0
    pub unk_seg_offset01: u64,
    pub header_offset: u64,
    pub prev_total_data_len: u64,
    pub total_data_len: u64,
    pub last_update: u64,
}
```
1. `total_data_len` is the size of data in all previous segments **and** this segment (data starts at `header_offset`, excludes optional 0-padding at the end of file)
2. `prev_total_data_len` is `total_data_len` in the previous file/segment

**Comment by michal-kapala** [comment]
`BigfileHeader` only exists in the first segment, the following should be stripped off `SegmentHeader`s and padding then appended

**Comment by michal-kapala** [comment]
`BigfileHeader` data for reference

## GRFS

![grfs big header](https://github.com/user-attachments/assets/c6db8146-ab38-4069-a0de-6a946eb1573e)

## GRO

![gro big header](https://github.com/user-attachments/assets/4ac22137-863e-48ac-a9ef-00d2d66e2559)

**Comment by electroball09** [comment]
okay this all looks right, I merged the changes.

I downloaded GRFS to take a look at the files, there does seem like an issue with the way the GRFS bigfiles work.

all Yeti objects are referenced by key, for instance the key 0x4e100b51 is referenced in the `all_levels.txt` file in GRFS folder. this same key is used in the GRO/P bigfiles, I guess as a universal package for the UI files. the file's name is given as "GlobalUI"

however, searching each GRFS bigfile yields no results for this key (search 510b104e for endianness). however if you search the GRO bigfile you will jump to the file table entry. 

another thing is the GRFS bigfiles don't seem to reference file names or paths like the GRO bigfile does. tbh it never really made sense to include that information in a release build, but they did for GRO. the more sensible option would be to include key and offset for each file, essentially the minimum amount of data needed for the engine to function, however I'm unable to locate file keys that should be present.

there's also a `dlc.big` under the DLC folder in GRFS files. this bigfile has the same `0x87` version as the main bigfiles, however file names are clearly present in the file table. this may indicate that GRFS bigfiles are encrypted somehow, given that file keys are critical for the engine and can't be properly located in the bigfiles. if that's the case we may be able to decrypt the file names and folder structure, given the right key.

**Comment by electroball09** [comment]
actually I just remembered Ubi called all PC players pirates. [here's](https://www.rockpapershotgun.com/piracy-stops-ghost-recon-future-soldier-pc) an article on that from 2011. it does make sense they might obfuscate file information to dissuade data mining.
